// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIvJ-GfCmQwr9-3IrJrx4-RB80q__c1ec',
    appId: '1:34611545604:web:d0f5b445e559bcf4fd5751',
    messagingSenderId: '34611545604',
    projectId: 'home-services-7d22e',
    authDomain: 'home-services-7d22e.firebaseapp.com',
    storageBucket: 'home-services-7d22e.appspot.com',
    measurementId: 'G-P7VDPZ09GW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtjA6OFaoWeweAkXJB15_edByfRiZmV6U',
    appId: '1:34611545604:android:97856755853d69a8fd5751',
    messagingSenderId: '34611545604',
    projectId: 'home-services-7d22e',
    storageBucket: 'home-services-7d22e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcpJDRUk4BnIXXzTq-vECcTB81QOLsgrk',
    appId: '1:34611545604:ios:5d6bf8c4885d72f1fd5751',
    messagingSenderId: '34611545604',
    projectId: 'home-services-7d22e',
    storageBucket: 'home-services-7d22e.appspot.com',
    iosClientId: '34611545604-rug8lrcpk1072ia4753gbms5ri7r5n05.apps.googleusercontent.com',
    iosBundleId: 'com.example.day35',
  );
}
